using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RapakMaliyetRapor.Core.Entity;

public class MuhasebeFisHareket
{
    public int Row_ID { get; set; }
    public string AltHesapKodu { get; set; }
    public string AltHesapAdi { get; set; }
    public decimal DonemselDevirBorc { get; set; }
    public decimal DonemselDevirAlacak { get; set; }
    public decimal DevirBorc { get; set; }
    public decimal DevirAlacak { get; set; }
    public decimal AcilisBorc { get; set; }
    public decimal AcilisAlacak { get; set; }
    public decimal KapanisBorc { get; set; }
    public decimal KapanisAlacak { get; set; }
    public string GirenKaynak { get; set; }
    public DateTime GirenTarih { get; set; }
    public string GirenSaat { get; set; }
    public string GirenKodu { get; set; }
    public string GirenSurum { get; set; }
    public string DegistirenKaynak { get; set; }
    public DateTime DegistirenTarih { get; set; }
    public string DegistirenSaat { get; set; }
    public string DegistirenKodu { get; set; }
    public string DegistirenSurum { get; set; }
    public decimal AylikBorcAlacakAylikBorc1 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak1 { get; set; }
    public decimal AylikBorcAlacakAylikBorc2 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak2 { get; set; }
    public decimal AylikBorcAlacakAylikBorc3 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak3 { get; set; }
    public decimal AylikBorcAlacakAylikBorc4 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak4 { get; set; }
    public decimal AylikBorcAlacakAylikBorc5 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak5 { get; set; }
    public decimal AylikBorcAlacakAylikBorc6 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak6 { get; set; }
    public decimal AylikBorcAlacakAylikBorc7 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak7 { get; set; }
    public decimal AylikBorcAlacakAylikBorc8 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak8 { get; set; }
    public decimal AylikBorcAlacakAylikBorc9 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak9 { get; set; }
    public decimal AylikBorcAlacakAylikBorc10 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak10 { get; set; }
    public decimal AylikBorcAlacakAylikBorc11 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak11 { get; set; }
    public decimal AylikBorcAlacakAylikBorc12 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak12 { get; set; }
    public decimal AylikBorcAlacakAylikBorc13 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak13 { get; set; }
    public decimal AylikBorcAlacakAylikBorc14 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak14 { get; set; }
    public decimal AylikBorcAlacakAylikBorc15 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak15 { get; set; }
    public decimal AylikBorcAlacakAylikBorc16 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak16 { get; set; }
    public decimal AylikBorcAlacakAylikBorc17 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak17 { get; set; }
    public decimal AylikBorcAlacakAylikBorc18 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak18 { get; set; }
    public decimal AylikBorcAlacakAylikBorc19 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak19 { get; set; }
    public decimal AylikBorcAlacakAylikBorc20 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak20 { get; set; }
    public decimal AylikBorcAlacakAylikBorc21 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak21 { get; set; }
    public decimal AylikBorcAlacakAylikBorc22 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak22 { get; set; }
    public decimal AylikBorcAlacakAylikBorc23 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak23 { get; set; }
    public decimal AylikBorcAlacakAylikBorc24 { get; set; }
    public decimal AylikBorcAlacakAylikAlacak24 { get; set; }
    public string OzelKodu { get; set; }
    public string GrupKodu { get; set; }
    public string HesapTipi { get; set; }
    public string MasrafMerkeziKodu { get; set; }
    public string HesapKodu2 { get; set; }
    public string HesapAdi2 { get; set; }
    public string DovizCinsi { get; set; }
    public decimal DovizDonemselBorc { get; set; }
    public decimal DovizDonemselAlacak { get; set; }
    public decimal DovizDevirBorc { get; set; }
    public decimal DovizDevirAlacak { get; set; }
    public decimal DovizAcilisBorc { get; set; }
    public decimal DovizAcilisAlacak { get; set; }
    public decimal DovizKapanisBorc { get; set; }
    public decimal DovizKapanisAlacak { get; set; }
    public decimal DovizAylikBorc1 { get; set; }
    public decimal DovizAylikAlacak1 { get; set; }
    public decimal DovizAylikBorc2 { get; set; }
    public decimal DovizAylikAlacak2 { get; set; }
    public decimal DovizAylikBorc3 { get; set; }
    public decimal DovizAylikAlacak3 { get; set; }
    public decimal DovizAylikBorc4 { get; set; }
    public decimal DovizAylikAlacak4 { get; set; }
    public decimal DovizAylikBorc5 { get; set; }
    public decimal DovizAylikAlacak5 { get; set; }
    public decimal DovizAylikBorc6 { get; set; }
    public decimal DovizAylikAlacak6 { get; set; }
    public decimal DovizAylikBorc7 { get; set; }
    public decimal DovizAylikAlacak7 { get; set; }
    public decimal DovizAylikBorc8 { get; set; }
    public decimal DovizAylikAlacak8 { get; set; }
    public decimal DovizAylikBorc9 { get; set; }
    public decimal DovizAylikAlacak9 { get; set; }
    public decimal DovizAylikBorc10 { get; set; }
    public decimal DovizAylikAlacak10 { get; set; }
    public decimal DovizAylikBorc11 { get; set; }
    public decimal DovizAylikAlacak11 { get; set; }
    public decimal DovizAylikBorc12 { get; set; }
    public decimal DovizAylikAlacak12 { get; set; }
    public decimal DovizAylikBorc13 { get; set; }
    public decimal DovizAylikAlacak13 { get; set; }
    public decimal DovizAylikBorc14 { get; set; }
    public decimal DovizAylikAlacak14 { get; set; }
    public decimal DovizAylikBorc15 { get; set; }
    public decimal DovizAylikAlacak15 { get; set; }
    public decimal DovizAylikBorc16 { get; set; }
    public decimal DovizAylikAlacak16 { get; set; }
    public decimal DovizAylikBorc17 { get; set; }
    public decimal DovizAylikAlacak17 { get; set; }
    public decimal DovizAylikBorc18 { get; set; }
    public decimal DovizAylikAlacak18 { get; set; }
    public decimal DovizAylikBorc19 { get; set; }
    public decimal DovizAylikAlacak19 { get; set; }
    public decimal DovizAylikBorc20 { get; set; }
    public decimal DovizAylikAlacak20 { get; set; }
    public decimal DovizAylikBorc21 { get; set; }
    public decimal DovizAylikAlacak21 { get; set; }
    public decimal DovizAylikBorc22 { get; set; }
    public decimal DovizAylikAlacak22 { get; set; }
    public decimal DovizAylikBorc23 { get; set; }
    public decimal DovizAylikAlacak23 { get; set; }
    public decimal DovizAylikBorc24 { get; set; }
    public decimal DovizAylikAlacak24 { get; set; }
    public string Birim { get; set; }
    public decimal DevredenStokGirisMiktari { get; set; }
    public decimal DevredenStokCikisMiktari { get; set; }
    public decimal DonDevStokGirisMiktari { get; set; }
    public decimal DonDevStokCikisMiktari { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari1 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari1 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari2 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari2 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari3 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari3 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari4 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari4 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari5 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari5 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari6 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari6 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari7 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari7 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari8 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari8 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari9 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari9 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari10 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari10 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari11 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari11 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari12 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari12 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari13 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari13 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari14 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari14 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari15 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari15 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari16 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari16 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari17 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari17 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari18 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari18 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari19 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari19 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari20 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari20 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari21 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari21 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari22 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari22 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari23 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari23 { get; set; }
    public decimal AylikMiktarlarStokGirisMiktari24 { get; set; }
    public decimal AylikMiktarlarStokCikisMiktari24 { get; set; }
    public DateTime? SonBorcTarihi { get; set; }
    public DateTime? SonAlacakTarihi { get; set; }
    public string Kod1 { get; set; }
    public string Kod2 { get; set; }
    public string Kod3 { get; set; }
    public string Kod4 { get; set; }
    public string Kod5 { get; set; }
    public string Kod6 { get; set; }
    public string Kod7 { get; set; }
    public decimal KDVOrani { get; set; }
    public string KDVHesapKodu { get; set; }
    public string MalHesabiparametresi { get; set; }
    public string FarkHesapKodu { get; set; }
    public bool ParasalFlag { get; set; }
    public bool FarkFlag { get; set; }
    public bool EnfDuzKaydi { get; set; }
    public DateTime? EnfDuzTarih { get; set; }
    public string VergiHesapNo { get; set; }
    public string VergiDairesi { get; set; }
    public string Ulke { get; set; }
    public bool FormBDurumu { get; set; }
    public string HesapAdiUnvanFlag { get; set; }
    public string Kod8 { get; set; }
    public string Kod9 { get; set; }
    public string Kod10 { get; set; }
    public bool EBelge { get; set; }
    public bool EnfDuzAcKayTarDegTabFlag { get; set; }
}